### ISSUE TITLE
slow perf on CompositionVisual sample

### ISSUE THREAD

**Issue by quincycs** [Microsoft/composition#11]
I couldn't get the actual sample to compile -
1>C:\Users\...\composition-master\SDK10586_NOV_UPDATE_RTM\CompositionVisual\compositionvisual\compositionvisual.csproj(128,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.16-beta\build\portable-net45+win8+wpa81\Microsoft.Diagnostics.Tracing.EventSource.Redist.targets.

- but I did get CompositionImageSample to work, then commented out its code and used the CompositionVisual code and got it to work.

That aside...

dragging with a mouse the rectangles is quite slow.  It doesn't move with the mouse seamlessly.  This a known issue?

**Comment by quincycs** [comment]
sorry, just tried this again, and the performance isn't that bad!

**Comment by sernaj** [comment]
Thanks for using the samples!
