### ISSUE TITLE
Geometric path animation support

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/composition#12]
I know this was mentioned in the BUILD 2015 but just wonder if there's a timeline for it? I am asking because if it's coming soon then I will wait for it otherwise I will have to find an alternative.

Thanks guys!

**Comment by patsiu** [comment]
Hey Justin!

Thanks for reaching out and sorry for a bit of a delay on the response. Unfortunately, "Not Soon" is your timeline for path animations, but we are thinking about them. If you have early feedback/scenarios in mind, feel free to send them our way!

**Comment by JustinXinLiu** [comment]
No worries @patsiu. :)

Basically I just want to animate the *points* of a shape and turn them into another shape. Real world examples would be, how a *three-line hamburger menu* icon gets transformed into a *back arrow* icon, or how a *circular* user profile background into a *rectangular* details background.
