### ISSUE TITLE
DrawingImage

### ISSUE THREAD

**Issue by Bortxx** [Microsoft/composition#16]
Can this API draw a XAML vector object 
`<DrawingImage><DrawingImage.Drawing><DrawingGroup>...`
as exported from Expression Design. Is there sample code for this?

**Comment by pgills** [comment]
Currently, there is no support for the XAML vector object (I think this is what you are referring to: https://msdn.microsoft.com/en-us/library/cc294508.aspx) using the Windows.UI.Composition API set.

**Comment by Bortxx** [comment]
I have a large WPF desktop app that I want to convert to UWP. All the artwork (which there is a lot of) was built in Expression Design and exported as XAML vector drawings which are imported as resources. So how do you work with vector drawings in UWP?

**Comment by Bortxx** [comment]
So what is the SpriteVisual's CompositionDrawingImage? Isn't that for XAML vector drawings?

**Comment by pgills** [comment]
`SpriteVisual` exposes a `CompositionBrush` via the `Brush` property. Examples of some brushes available are:
- `CompositionColorBrush` which is used for solid colors
- `CompositionEffectBrush` which is used for effects
- `CompositionSurfaceBrush` which is used for surfaces

Currently, `Windows.UI.Composition` does not have a CompositionDrawingImage type.

The `CompositionDrawingSurface` type is leveraged for rendering content like bitmaps, not XAML vector objects.

For truly custom rendered content you can leverage Win2D and CompositionDrawingSurface. Link to Win2D sample: [here](https://github.com/Microsoft/Win2D/blob/master/samples/CompositionExample/DrawingSurfaceRenderer.cs)

However, I don't believe that this addresses the question you asking, which is whether or not you can leverage vector objects exported from Expression Design in a UWP application?

I'm not that familiar with the types and format that Expression Design uses during export to answer your specific question; however, if those types are something like `Windows.UI.Xaml.Shapes` it might be possible to use them together with a `Windows.UI.Xaml.Controls.Canvas` in a UWP.

**Comment by Bortxx** [comment]
Win2D is not a retained mode model and Windows.UI.XAML.Controls.Canvas in UWP is not low level enough like the visual system in WPF. What Expression Design outputs is not specific to it but just standard XAML vector drawings. Here is an example:

`    <DrawingGroup x:Key="TrackCurved1_1">
        <DrawingGroup.Children>
            <GeometryDrawing Brush="#0036A3C0" Geometry="F1 M 549,51L 549,-1L 601,-1L 601,51L 549,51 Z "/>
            <GeometryDrawing Brush="#FFAAAAAA" Geometry="F1 M 593.5,48.5L 595,50C 595.833,50 596.667,50 597.5,49.5833C 598.333,49.1667 599.167,48.3333 599.583,47.5C 600,46.6667 600,45.8333 600,45L 598.531,43.5313C 581.5,26.5 578.5,19.0125 578.5,5.5L 578.5,3.5C 578,3 577.5,2.5 576.583,2.25C 575.667,2 574.333,2 573.417,2.25C 572.5,2.5 572,3 571.5,3.5L 571.5,5.5C 571.5,21 575.5,30.5 593.5,48.5 Z ">
                <GeometryDrawing.Pen>
                    <Pen LineJoin="Round" Brush="#FF000000"/>
                </GeometryDrawing.Pen>
            </GeometryDrawing>
        </DrawingGroup.Children>
    </DrawingGroup>`

WPF consumes this natively, and a lot more complex type drawings very nicely. The great advantage is that you can modify these drawings on the fly through a DOM once loaded from the resource files, they are hardware accelerated, they can be placed anywhere (XAML control contents, overlays, deep trees), they can be transformed and animated with visual loss, and all of that it in a retained mode. Expression Design, Photoshop, and other vector tool plugins can generate this XAML easy and be inserted in your WPF app with a simple cut and paste. So you're telling me there is no UWP equivalent? How are we suppose to move to this new platform when its so lacking?

**Comment by pgills** [comment]
Thanks for the DrawingGroup example. Unfortunately, I'm unaware of any replacement/equivalent for DrawingGroup from WPF.

**Comment by Bortxx** [comment]
I hope your team considers adding a method to draw these type of vector XAML objects. Its a perfect candidate for your API since it is the only retained graphics library akin to the WPF version.

**Comment by themoretheless** [comment]
Draw vector in UWP canvas
http://stackoverflow.com/a/36439591

**Comment by mfe-** [comment]
I wanted to use the power of a converted svg to XAML (which uses DrawingGroup, DrawingImage, GeometryDrawing - like the mentioned example [here](https://github.com/Microsoft/WindowsUIDevLabs/issues/16#issuecomment-182148607) ) to apply easily some animations.

Wouldn't it be possible to implement DrawingGroup, DrawingImage, GeometryDrawing by extending the classes of Windows.UI.XAML.Shapes (Line, Ellipse, Rectangle, Path,...)?

**Comment by CrimsonArc** [comment]
@themoretheless 
That method you mentioned is not equal to WPF DrawingImage, by use WPF DrawingImage, you can set it as Image control's source, and then change the Image control's pixel size to scale your vector image to any pixel size you want. This is awesome for vector image scaling scenarios. But UWP can't do this.
