### ISSUE TITLE
Unable to run TransformComponents

### ISSUE THREAD

**Issue by dachibox** [Microsoft/composition#17]
Method not found: 'System.Object Windows.UI.Xaml.Hosting.ElementCompositionPreview.GetContainerVisual(Windows.UI.Xaml.UIElement)'.

System.MissingMethodException: Method not found: 'System.Object Windows.UI.Xaml.Hosting.ElementCompositionPreview.GetContainerVisual(Windows.UI.Xaml.UIElement)'.
   at TransformComponents.MainPage.MainPage_Loaded(Object sender, RoutedEventArgs e)

**Comment by msftdavid** [comment]
It sounds like you might be on an updated (Nov Update) build of Windows running the old 10240 sample. Could you try running the TransformComponents sample in the 10586 folder?

**Comment by pgills** [comment]
Haven't seen any traction on this, please reopen if you are still running into the above issue. Thanks!
