### ISSUE TITLE
Known Issue: SpriteVisuals do not render in Insider Build 10.0.14257

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/composition#18]
I was able to run the samples yesterday but today after installing the new Windows 10 build *10586.104* whatever projects that use *Microsoft.UI.Composition.Toolkit* to load images are not able to display any images at all.

**Comment by krt-** [comment]
Same happened with 14257 build

**Comment by JustinXinLiu** [comment]
Actually I meant Version *10.0.14257* too. I was confused about the version number... Thanks @krt- :)

**Comment by sernaj** [comment]
We're looking at this. Thanks for the heads up.

**Comment by pgills** [comment]
@JustinXinLiu, just to confirm, are you seeing this just for samples using image loading, or any sample that's using a SpriteVisual and a Brush like the [CompositionVisual](https://github.com/Microsoft/composition/tree/master/SDK10586_NOV_UPDATE_RTM/CompositionVisual) sample?

**Comment by JustinXinLiu** [comment]
You are right @pgills, the CompositionVisual sample loads up empty. So it's not just image loading ones but any sample that's using a `SpriteVisual` and a `Brush`.

**Comment by pgills** [comment]
Thanks @JustinXinLiu for the verification, and thanks for continuing to give us feedback on `Windows.UI.Composition`. 

We've root caused the `SpriteVisual` rendering issue we'll addressing and fixing it in a subsequent insider build.

**Comment by JustinXinLiu** [comment]
Confirm this has been fixed in build `14267`. :+1:

**Comment by pgills** [comment]
Awesome. Thanks!
