### ISSUE TITLE
SlideShow sample code is not building

### ISSUE THREAD

**Issue by balrajOla** [Microsoft/composition#3]
When i have cloned the entire code and build for the first time I am getting below error. I have rebuilded cleaned and done everything. Please help.

![image](https://cloud.githubusercontent.com/assets/12622119/7831299/057e1ed2-0473-11e5-91a7-c22e82ac0058.png)

**Comment by likuba** [comment]
This should now be fixed :) Thanks for letting us know!

**Comment by balrajOla** [comment]
Thanks likuba its working now... :)
