### ISSUE TITLE
Unable to run the SlideShow sample: Unhandled exception

### ISSUE THREAD

**Issue by agenne** [Microsoft/composition#6]
Unable to cast object of type 'Windows.UI.Composition.ContainerVisual' to type 'Windows.UI.Composition.IVisual'.

**Comment by sernaj** [comment]
Sorry about the delay in answering your issue, we had a few problems getting pings back from our GitHub when issues were posted.

This error can occur when a project is not targeting the latest build and SDK in VS2015. Make sure you're on build 10586 and under Project>Properties you're targeting SDK for 10856. We have also noticed that sometimes VS and the SDK get in a bad state and VS and the SDK both need to be reinstalled. 

Once again sorry about the delay.
