### ISSUE TITLE
Composition.StopAnimation not working

### ISSUE THREAD

**Issue by limefrogyank** [Microsoft/composition#7]
I've got an ExpressionAnimation running on an CompositionEffectBrush that changes the hue of a visual.  The expression is using the ScrollerViewManipulation property, Translation.Y.  I've also created a scalar property to hold the ScrollViewer's ScrollableHeight, so I can get a normalized scroll position.  

I'm handling the Window.Current.SizeChanged event and trying to update the parameters of my ExpressionAnimation since the ScrollViewer's ScrollableHeight has changed.  However, I can't seem to change it.  I've tried to stop the animation, change the parameter, then restart it, but nothing seemed to change.  Then I just tried to stop the animation when the window changes size like this:

````
_effectBrush.Properties.StopAnimation("HueRotationEffect.Angle");
````
and nothing happens.  The animation continues to play.

*edit*
I've just tried to stop any of my animations, including the parallax animation that was demoed by one of your team, and I can't get it to stop once started.

````
_visual.StopAnimation("Offset.Y");
````
again, this has no effect.

**Comment by patsiu** [comment]
Thanks for bringing this to our attention - sorry you've having issues with StopAnimation(). We're looking into this and we'll circle back here once we have something concrete from our investigation. Stay tuned.

**Comment by patsiu** [comment]
We took a look into this issue and didn't find suspicious on our end, but we're very interested into why this occurring for you. Can you start an email thread with us (WinComposition@microsoft.com) and we'll dive into this further. Thanks!

**Comment by limefrogyank** [comment]
Sorry, I haven't been able to get back to this.  For now, I'll just close the issue and reopen it if I have time to recheck my problem.
